from fpdf import FPDF
import matplotlib.pyplot as plt
import tempfile
import os
import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'FinAI Robo-Advisor - Investment Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_report(user_profile, weights, tickers, metrics, simulation_summary=None):
    """
    Generates a PDF investment report.
    
    Args:
        user_profile (dict): Risk profile data.
        weights (list): Portfolio weights.
        tickers (list): Asset tickers.
        metrics (dict): {'return': float, 'volatility': float, 'sharpe': float}.
        simulation_summary (dict): Optional Monte Carlo summary.
        
    Returns:
        bytes: PDF file content.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- Timestamp ---
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'R')
    pdf.ln(5)
    
    # --- Client Profile ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, "Client Profile", 0, 1)
    
    pdf.set_font("Arial", size=11)
    pdf.cell(50, 8, f"Risk Score: {user_profile['score']}", 0, 0)
    pdf.cell(50, 8, f"Risk Level: {user_profile['risk_level']}", 0, 1)
    pdf.cell(0, 8, f"Description: {user_profile['description']}", 0, 1)
    pdf.ln(5)
    
    # --- Performance Metrics ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, "Projected Performance", 0, 1)
    
    pdf.set_font("Arial", size=11)
    pdf.cell(60, 8, f"Expected Annual Return: {metrics['return']:.2%}", 0, 0)
    pdf.cell(60, 8, f"Expected Volatility: {metrics['volatility']:.2%}", 0, 1)
    pdf.cell(60, 8, f"Sharpe Ratio: {metrics['sharpe']:.2f}", 0, 1)
    pdf.ln(5)
    
    # --- Allocation Chart (Matplotlib) ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(100, 10, "Portfolio Allocation", 0, 1)
    
    # Filter weights > 1%
    labels = []
    sizes = []
    for t, w in zip(tickers, weights):
        if w > 0.01:
            labels.append(f"{t}")
            sizes.append(w)
            
    try:
        # Create plot
        plt.figure(figsize=(6, 4))
        plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140)
        plt.axis('equal')
        plt.title('Recommended Asset Mix')
        
        # Save to temp file
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmpfile:
            plt.savefig(tmpfile.name, bbox_inches='tight')
            tmp_chart_path = tmpfile.name
        
        plt.close() # Close figure to free memory
        
        # Insert into PDF
        # Image w=100 (half page width roughly)
        pdf.image(tmp_chart_path, x=20, w=170) 
        pdf.ln(5)
        
        # Cleanup
        os.unlink(tmp_chart_path)
    except Exception as e:
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(0, 10, f"Chart generation failed: {e}", 0, 1)

    pdf.ln(5)
    
    # --- Monte Carlo Summary ---
    if simulation_summary:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(100, 10, "10-Year Monte Carlo Projection", 0, 1)
        
        pdf.set_font("Arial", size=11)
        pdf.cell(0, 8, f"Optimistic (95th Percentile): ${simulation_summary['95th Percentile']:,.2f}", 0, 1)
        pdf.cell(0, 8, f"Median (50th Percentile): ${simulation_summary['50th Percentile']:,.2f}", 0, 1)
        pdf.cell(0, 8, f"Pessimistic (5th Percentile): ${simulation_summary['5th Percentile']:,.2f}", 0, 1)
        pdf.ln(5)
        
    # --- Disclaimer ---
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 5, "DISCLAIMER: This report is generated by an AI Robo-Advisor for educational purposes only. It does not constitute financial advice. Investment involves risk, including possible loss of principal. Please consult a qualified financial advisor before making investment decisions.")
    
    return pdf.output(dest='S').encode('latin-1')
